workflows:
  ios-workflow:
    name: Build iOS IPA without signing
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa