workflows:
  ios-workflow:
    name: Build iOS IPA without signing
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS App and create IPA
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Payload.ipa Payload
    artifacts:
      - build/ios/iphoneos/Payload.ipa