workflows:
  web-workflow:
    name: Build Flutter Web
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Build Web
        script: |
          flutter packages pub get
          flutter build web --release
    artifacts:
      - build/web/**